//System
export const CHANGE_LANGUAJE = 'CHANGE_LANGUAGE';

//ProductDetail
export const TOOGLE_PRODUCT_DETAIL_MODAL = 'TOOGLE_PRODUCT_DETAIL_MODAL';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';

//AddProduct
export const TOOGLE_ADD_PRODUCT_MODAL = 'TOOGLE_ADD_PRODUCT_MODAL';

//EditProduct
export const TOOGLE_EDIT_PRODUCT_MODAL = 'TOOGLE_EDIT_PRODUCT_MODAL';

//SearchProducts
export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST';
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAILED = 'PRODUCT_SEARCH_FAILED';
export const PRODUCT_SEARCH_RESET = 'PRODUCT_SEARCH_RESET';